  // printf("...............deleting from first.......................\n");
    // displayList();
    // deletionFromBeg();
    // displayList();
    // deletionFromBeg();
    // displayList();
    // deletionFromBeg();
    // displayList();
    // deletionFromBeg();
    // displayList();